### ISSUE TITLE
对于ATS-A模块，是不是用不到fastalign？它的训练过程和-NE的差别是不是只有这块？

### ISSUE THREAD

**Issue by XL2248** [ZNLP/ATSum#2]
作者你好，我想问下，
对于ATS-A模块，是不是用不到fastalign？ATS-A的训练过程和ATS-NE的差别是不是只有这块？
ATS-A运行过程是怎样的?

**Comment by Zhujunnan** [comment]
sorry，最近有点忙，回复不及时还请见谅！词对齐主要是帮助挑出翻译候选，ATS-A和另外两个差别就在于增加了对于翻译候选的attention上，其余的运行过程是一样的。如果上述没有解决你的疑问，欢迎发邮件与我（junnan.zhu@nlpr.ia.ac.cn）沟通。
