### ISSUE TITLE
提供不同模型的输出的Rouge值和论文不匹配

### ISSUE THREAD

**Issue by Encyclomen** [ZNLP/ATSum#4]
想问一下，我用了本代码中提供rouge.sh步骤测量了不同模型的输出(ats-m1, ats-m5, ats-m10, tncls)，得到的rouge-1, rouge-2, rouge-L值与论文中不匹配，rouge-L明显偏低，请问可能是什么原因呢？所提供的模型输出是论文中所报结果对应的输出吗？

**Comment by Zhujunnan** [comment]
你好，有可能是files2rouge的问题，可以检查一下files2rouge的版本
